apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cattle-system
  name: pod-list-and-exec-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get", "create", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-list-and-exec-rolebinding
  namespace: cattle-system
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: cattle-system
roleRef:
  kind: Role
  name: pod-list-and-exec-role
  apiGroup: rbac.authorization.k8s.io