apiVersion: batch/v1
kind: CronJob
metadata:
  name: rancher-token
  namespace: cattle-system
spec:
  schedule: "0 */3 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: rancher-token
        spec:
          serviceAccountName: vault-auth
          containers:
            - name: rancher-tokens
              image: lukaszbielinski/rancher-tokens
              imagePullPolicy: Always
              env:
                - name: RANCHER_SERVER
                  value: rancher.net
                - name: SKIP_TLS_VERIFY
                  value: "true"
                - name: VAULT_ADDR
                  value: vaultAdress
                - name: VAULT_SECRET_ENGINE
                  value: kv-v2
                - name: VAULT_SECRET_PATH
                  value: secretNAme
          restartPolicy: OnFailure
